# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool: Default
  #vmImage: ubuntu-latest
stages:
  - stage: GetTerraformManifests
    displayName: Build_Stage
    jobs:
      - job: BuildJob
        steps:
          - bash: echo "contents in working directoy"; ls -lrth $(System.DefaultWorkingDirectory)

          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)'
              Contents: '**'
              TargetFolder: '$(System.DefaultWorkingDirectory)'

          - bash: echo "contents in working directoy"; ls -lrth $(System.DefaultWorkingDirectory)
            displayName: List Contents post copying
          
          - task: PublishBuildArtifacts@1
            displayName: Publish Manifests to Release pipeline
            inputs:
              PathtoPublish: '(Build.ArtifactStagingDirectory)'
              ArtifactName: 'terraform-manifests'
              publishLocation: 'Container'
